 /*
  * This Java source file was generated by the Gradle 'init' task.
  */
 package edu.duke.ece651.team2.server;

 import java.io.IOException;


 public class App {

   /**
    * @throws IOException            when there are input or output exceptions
    * @throws ClassNotFoundException when there are class not found exceptions
    */
   public static void main(String[] args) throws IOException, ClassNotFoundException {
     Master master = new Master();
     master.initPlayers();
     master.playMultiTurns();
     master.closeSocket();
   }
 }
